In [15]:
import numpy as np
from qcodeplot3d.cc_3d import cubic_3d_dual_graph, tetrahedron_3d_dual_graph
from qcodeplot3d.cc_2d import triangular_2d_dual_graph, square_2d_dual_graph
from qcodeplot3d.common.stabilizers import get_check_matrix

def extract_matrices(code_type, distance):
    # 1. Construct the Dual Graph
    if code_type == "cubic":
        graph = cubic_3d_dual_graph(distance)
    elif code_type == "tetrahedral":
        graph = tetrahedron_3d_dual_graph(distance)
    elif code_type == "triangular":
        graph = triangular_2d_dual_graph(distance)
    elif code_type == "square":
        graph = square_2d_dual_graph(distance)
    else:
        raise ValueError("Unknown code type")

    # 2. Extract Stabilizers    
    x_stabilizers = [node.stabilizer for node in graph.nodes() if node.is_stabilizer]
    
    if "3d" in code_type or code_type in ["cubic", "tetrahedral"]:
        z_stabilizers = [edge.stabilizer for edge in graph.edges() if edge.is_stabilizer]
    else:
        z_stabilizers = x_stabilizers

    # 3. Generate Matrices    
    H_x = get_check_matrix(x_stabilizers, only_x=True)
    
    if "3d" in code_type or code_type in ["cubic", "tetrahedral"]:
        H_z = get_check_matrix(z_stabilizers, only_z=True)
    else:
        H_z = H_x

    return H_x, H_z

In [16]:
Hx, Hz = extract_matrices("tetrahedral", 3)
print(Hx)
print(Hz)

[[1 1 0 1 0 0 0 1 0 1 1 1 0 1 0]
 [1 0 1 1 0 1 1 0 1 0 1 1 0 0 0]
 [1 0 0 0 0 0 1 0 1 1 0 1 1 1 1]
 [0 0 0 1 1 1 1 1 0 1 0 1 0 0 1]]
[[0 1 0 1 0 0 0 1 0 0 1 0 0 0 0]
 [0 0 1 1 0 1 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 1 1 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 1 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 1 1]
 [0 0 0 0 1 0 0 1 0 1 0 0 0 0 1]
 [0 0 1 0 0 1 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 0 1 0 1]
 [0 0 0 0 1 1 1 0 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 0 0 0 1 0 0 1 0]
 [1 0 1 0 0 0 0 0 1 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0 0 0 1 1 0]
 [1 0 0 0 0 0 1 0 1 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 1 0 1 0 1 0]
 [1 0 0 1 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 1 0 1 0 0 1]
 [0 0 0 1 0 1 1 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 1 0 1 0 1 0 0 0]]
